spring.application.name=sb01_JspOracleMybatis

## 서버 관련 설정
# 서버 포트 변경 (기본값은 8080임)
server.port=3306
# 서버 재시작 시 세션 유지 여부 등
server.servlet.session.timeout=30m

## 데이터베이스 설정
# DB 접속 정보
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//127.0.0.1:1521/xe
spring.datasource.username=scott
spring.datasource.password=tiger

## JSP 뷰 리졸버(view Resolver)설정
# JSP 파일 경로 및 확장자 설정
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

## 데이터베이스 설정
# 매퍼 XML 파일 위치 설정(src/main/resources 하위 기준)
mybatis.mapper-locations=classpath:mybatis/mapper/**/*.xml

## 로깅(Logging) 설정
# 로그 레벨 설정(디버깅 시 유용)
logging.level.org.springframework=info
logging.level.com.doit.app=debug